name: laticifer-env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - scikit-image
  - matplotlib
  - pandas
  - napari
  - pyside6
  - pytorch
  - torchvision
  - cudatoolkit=11.8   # remove this line if CPU only
  - pip
  - pip:
      - segmentation-models-pytorch
      - albumentations
      - opencv-python-headless